[theme]
base = "light"
backgroundColor = "#F0F2F6"  # Light gray background
secondaryBackgroundColor = "#E0E0E0"  # Sidebar or secondary areas
textColor = "#000000"  # Black text for readability
font = "sans serif"